CREATE DATABASE IF NOT EXISTS RECORDINGS ;
USE RECORDINGS ;

CREATE TABLE IF NOT EXISTS recordings
(
ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
URL VARCHAR(1024) NOT NULL UNIQUE,
RATING INT(1)
);

q = """INSERT INTO recordings (URL, RATING)
values
("http://readonlywriting.org/recorings", NULL)"""
